# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      npm install
      cd client
      npm install
    command: |
      npm run dev

ports:
  - port: 5000
    visibility: public
    onOpen: ignore
  - port: 5173
    visibility: public
    onOpen: ignore

github:
  prebuilds:
    master: true
